# Generated by Django 5.2 on 2025-05-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fincontrol_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
