# Generated by Django 5.2 on 2025-05-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincontrol_api', '0002_remove_transacao_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-06 00:00:00'),
            preserve_default=False,
        ),
    ]
